# Generated by Django 4.2.6 on 2023-10-17 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('userauths', '0003_rename_user_user_reg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_reg',
            new_name='User',
        ),
    ]
