# Generated by Django 4.2.6 on 2023-11-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_language_product_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='languages',
            field=models.ManyToManyField(to='admin_panel.language'),
        ),
    ]
