# Generated by Django 4.2.6 on 2023-11-07 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_categories_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='product',
            name='languages',
        ),
        migrations.CreateModel(
            name='ProductLanguageVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.language')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.product')),
            ],
        ),
    ]
