# Generated by Django 4.2.6 on 2023-11-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_remove_product_price_remove_product_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlanguagevariation',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
