# Generated by Django 4.2.6 on 2023-11-05 11:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_order_order_notes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('customer', 'complete')},
        ),
    ]
