# Generated by Django 4.2.6 on 2023-11-11 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_remove_productlanguagevariation_price_product_price'),
        ('shop', '0008_orderitem_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivery_status',
            field=models.CharField(choices=[('PL', 'Order placed'), ('DS', 'Dispatched'), ('SH', 'Shipped'), ('OFD', 'Out for Delivery'), ('CN', 'Order Cancelled')], default='PL', max_length=3),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variation', to='admin_panel.productlanguagevariation'),
        ),
    ]
