# Generated by Django 4.2.6 on 2023-11-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_orderitem_delivery_status_alter_orderitem_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='delivery_status',
            field=models.CharField(choices=[('PL', 'Order placed'), ('DS', 'Dispatched'), ('SH', 'Shipped'), ('OFD', 'Out for Delivery'), ('D', 'Delivered'), ('CN', 'Order Cancelled'), ('RT', 'Returned')], default='PL', max_length=3),
        ),
    ]
