# Generated by Django 4.2.6 on 2023-11-23 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
