# Generated by Django 4.2.6 on 2023-12-11 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0018_product_date_added'),
        ('shop', '0016_delete_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variations', to='admin_panel.productlanguagevariation'),
        ),
    ]
