# Generated by Django 4.2.6 on 2023-11-17 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_wallet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
